version: '3'
services:
  backend:
    build: ./server
    ports:
      - "3031:3031"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3031/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    build: ./client
    ports:
      - "3030:3030"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3030/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
