version: '3'
services:
  backend:
    build: ./server
    expose:
      - "3031"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend:3031/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    build: ./client
    expose:
      - "3030"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://frontend:3030/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
        max_attempts: 3

  nginx:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
networks:
  default:
    driver: bridge
    name: SystemMonitoring
